[env]
TERM = "alacritty"

[window]
padding = { x = 10, y = 10 }
opacity = 0.94

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.0

[colors.primary]
background = "#0a0a0a"
foreground = "#e0e0e0"

[colors.cursor]
text = "#0a0a0a"
cursor = "#FF244C"

[colors.selection]
text = "#f0f0f0"
background = "#B81D3A"

[colors.normal]
black =   "#1a1a1a"
red =     "#FF244C"
green =   "#50C878"
yellow =  "#FFD700"
blue =    "#61AFEF"
magenta = "#FF244C"
cyan =    "#56B6C2"
white =   "#e0e0e0"

[colors.bright]
black =   "#3d3d3d"
red =     "#FF244C"
green =   "#62E091"
yellow =  "#FFEE58"
blue =    "#7EC8F8"
magenta = "#FF244C"
cyan =    "#70CAD1"
white =   "#f0f0f0"

[bell]
animation = "EaseOutExpo"
duration = 100
color = "#FF244C"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
