#!/usr/bin/env bash
# This script generates the Hyprland execs configuration file (execs.conf).
# This file lists commands and applications that Hyprland should execute once upon startup.
# It uses helper functions from 'common.sh'.
set -euo pipefail

# Source common library functions for configuration file management.
source "$(dirname "$0")/../config_lib/common.sh"

# Define the target path for the Hyprland execs configuration file.
# HYPR_CONF_TARGET_DIR is expected to be an environment variable.
TARGET_FILE="$HYPR_CONF_TARGET_DIR/execs.conf"

# Prepare the target file for writing.
prepare_target_file_write "$TARGET_FILE" "Hyprland Execs"

# Define defaults for cursor settings if environment variables TARGET_CURSOR_THEME or TARGET_CURSOR_SIZE are not set.
# These are used by this script to set the cursor theme via hyprctl.
EFFECTIVE_TARGET_CURSOR_THEME="${TARGET_CURSOR_THEME:-Bibata-Modern-Classic}"
EFFECTIVE_TARGET_CURSOR_SIZE="${TARGET_CURSOR_SIZE:-24}"

# Note on HYPR_SCRIPTS_DIR:
# The 'cat << EOF' block below will write the literal string '\$HYPR_SCRIPTS_DIR'.
# Hyprland itself will expand this variable at runtime, using the value
# set in its environment (presumably from env.conf, which is generated by hyprland_env.sh).

# Use a 'here document' to write the exec-once commands.
cat << EOF > "$TARGET_FILE"
# Commands to execute once when Hyprland starts.

# Update D-Bus activation environment for systemd services to be aware of Wayland.
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# Import Wayland and XDG environment variables into the systemd user session.
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Start essential desktop components
exec-once = waybar &                                 # Start the Waybar status bar
exec-once = hyprpaper &                              # Start Hyprpaper for wallpaper management
exec-once = mako &                                   # Start Mako notification daemon

# Start the idle configuration script (for screen locking, suspend, etc.)
# \$HYPR_SCRIPTS_DIR is an environment variable that should be set by Hyprland (via env.conf)
# to point to the directory containing custom helper scripts.
exec-once = \$HYPR_SCRIPTS_DIR/idle_config.sh &

# Start Polkit authentication agent (provides privilege escalation dialogs for GUI apps)
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # Path may vary by distribution

# Clipboard manager integration: store text and image clipboard history.
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Set the cursor theme and size using hyprctl.
# This ensures the cursor theme is applied correctly within Hyprland.
exec-once = hyprctl setcursor ${EFFECTIVE_TARGET_CURSOR_THEME} ${EFFECTIVE_TARGET_CURSOR_SIZE}
EOF

# Finalize the write operation for the target file.
finish_target_file_write "$TARGET_FILE" "Hyprland Execs"
